# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6db026aae671b4b571a33045823d78130dea39ba47b70df3ed7b2e7ab2cb41d0e08a16c94c8272e6b836fe79e65869e14938f95a21a394ec4fecfe6931d15e04

test:
  secret_key_base: f5bb45aa83838b529bcb22a9af4234dc60f827cfe90ab6c94be23256cae3c2522ab0b1a2c4cfcdbd09072499f15087bac25186afc4695b3d22e88f97bc37b71e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
